name: lamp-stack
on: [push]
permissions: read-all
jobs:
  kics:
    name: 'KICS'
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v2.1.3
        with:
          path: 'Terraform'
          ignore_on_exit: results
          output_path: myResults/
      - name: display kics results
        run: |
          cat myResults/results.json
  terraform:
    name: 'Terraform'
    needs: kics
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Plan
      run: terraform plan -input=false
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve